name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: 更新版本資訊（產生 version.js 並更新 index.html/manifest.json）
        run: node scripts/update-version.mjs
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
          BUILD_NUMBER:    ${{ github.run_number }}
          GIT_SHA:         ${{ github.sha }}
      - run: npm test
